### ISSUE TITLE
Ember-addon with broccoli-debug fails with unknown error

### ISSUE THREAD

**Issue by lebbers** [broccolijs/broccoli-debug#8]
I have a created a new ember addon (using ember-cli version 2.13.3)  to test this utility but it directly fails with the following error:

```
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: Addon#treeFor (test-addon - app)] failed with:
Error: Build Canceled: Broccoli Builder ran into an error with BroccoliDebug plugin. 💥
    at new BroccoliBuildError (C:\Projects\temp\test-addon\node_modules\broccoli-builder\lib\broccoli-build-error.js:40:9)
    at C:\Projects\temp\test-addon\node_modules\broccoli-builder\lib\builder.js:168:19
    at tryCatch (C:\Projects\temp\test-addon\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Projects\temp\test-addon\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\Projects\temp\test-addon\node_modules\rsvp\dist\rsvp.js:522:7)
    at publishRejection (C:\Projects\temp\test-addon\node_modules\rsvp\dist\rsvp.js:457:3)
    at flush (C:\Projects\temp\test-addon\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (C:\Projects\temp\test-addon\node_modules\broccoli-plugin\index.js:7:31)
    at new BroccoliMergeTrees (C:\Projects\temp\test-addon\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (C:\Projects\temp\test-addon\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:10:53)
    at mergeTrees (C:\Projects\temp\test-addon\node_modules\ember-cli\lib\broccoli\merge-trees.js:85:33)
    at Class.treeFor (C:\Projects\temp\test-addon\node_modules\ember-cli\lib\models\addon.js:490:30)
    at project.addons.map.addon (C:\Projects\temp\test-addon\node_modules\ember-cli\lib\broccoli\ember-app.js:559:22)
    at Array.map (native)
    at EmberAddon.addonTreesFor (C:\Projects\temp\test-addon\node_modules\ember-cli\lib\broccoli\ember-app.js:557:32)
    at EmberAddon._processedAppTree (C:\Projects\temp\test-addon\node_modules\ember-cli\lib\broccoli\ember-app.js:852:27)
    at EmberAddon.appAndDependencies (C:\Projects\temp\test-addon\node_modules\ember-cli\lib\broccoli\ember-app.js:1114:12)
```

I have the following index.js file.

```
const BroccoliDebug = require('broccoli-debug');

module.exports = {
  name: 'test-addon',

  treeForApp(...rest) {
    let tree = this._super(...rest);

    const debugTree = BroccoliDebug.buildDebugCallback(`test:${this.name}`);
    return debugTree(tree, 'treeFor');
  }
};
```

command executed is `BROCCOLI_DEBUG=test:* ember b`

Any clues what I'm doing wrong here or how I could find the original error?

**Comment by krisselden** [comment]
This should be fixed by #10
